project:
  type: website

website:
  title: "LuisR"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: research.qmd
        text: Research

format:
  html:
    theme: lumen
    css: styles.css
    toc: true

editor: visual

